### ISSUE TITLE
Cannot download BarcodeScannerView higher than 1.3.0

### ISSUE THREAD

**Issue by pramuko** [markusfisch/BarcodeScannerView#3]
Hi,

I added your library with the usual jitpack in root build.gradle 

`maven { url "https://jitpack.io" }`

and this line in app build.gradle:

`implementation 'com.github.markusfisch:BarcodeScannerView:$version'`

However I always failed if I put any version of 1.4.0, 1.4.1, and 1.5.0 as listed in jitpack.io website. I only succeeded after I set 1.3.0 version. Thanks.

**Comment by markusfisch** [comment]
Ah, sorry, this was fixed with the latest commit but I forgot to set a tag 🙈I'm away for a couple of days and will only be able to fix next week, unfortunately. In the meantime you could clone the repo and build the aar manually (just run "make aar").Sorry, I will fix it as soon as possible.

**Comment by markusfisch** [comment]
Version 1.5.1 is now available in [JitPack](https://jitpack.io/#markusfisch/BarcodeScannerView/1.5.1).
